= Feature Names Tests

This repository contains data, scripts and documentation for the testing of the Queensland Spatial Information (QSI) https://linked.data.gov.au/def/addr[_Address Model_].

The specific tests, how they work and what they are for, are described in the documentation within the `tests/` folder.


== Rights and License

Content generated by Spatial Information Queensland is copyright as follows:

&copy; The State of Queensland (Department of Resources) 2023

This information is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.


== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +
Queensland Government +
CadastralAdminDataHelp@resources.qld.gov.au

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +
https://qldspatial.information.qld.gov.au/

For technical implementation questions, contact the engineering consultancy that created this repository:

*KurrawongAI* +
info@kurrawong.ai +
https://kurrawong.ai +
