= Feature Names Tests

This repository contains static data, stored queries and application code used to test the _Feature Names_ system established for Queensland Spatial Information (QSI) in 2023.



== Rights and License

Content generated by Spatial Information Queensland is copyright as follows:

&copy; The State of Queensland (Department of Resources) 2023

This information is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

Much of the vocabulary content here is copied from elsewhere and, where this has occurred, the vocabulary source is noted so that the source information licensing and rights may be discovered.

== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +
Queensland Government +
CadastralAdminDataHelp@resources.qld.gov.au

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +
https://qldspatial.information.qld.gov.au/

For technical implementation questions, contact:

*Nicholas Car* +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._
