# Get a count of the number of addressable objects (parcels) in the graph.

PREFIX addr: <https://w3id.org/profile/anz-address/>
SELECT (COUNT(?iri) as ?count)
WHERE {
    ?iri a addr:AddressableObject .
}